#------------------------------------------------------------------------------
# <autogenerated>
#     This code was generated by a tool.
#     Runtime Version: 4.0.30319.42000
#
#     Changes to this file may cause incorrect behavior and will be lost if 
#     the code is regenerated.
# </autogenerated>
#------------------------------------------------------------------------------

import System.Windows.Forms
import clr

class MyForm_Designer(System.Windows.Forms.Form):
    
    def InitializeComponent(self):
        resources = PythonResourceManager("MyForm_Designer", scriptContext)
        self.SuspendLayout()
        # 
        # MyForm_Designer
        # 
        self.ClientSize = System.Drawing.Size(1014, 703)
        self.Name = "MyForm_Designer"
        self.Text = "Hello"
        self.ResumeLayout(False)
