#------------------------------------------------------------------------------
# <autogenerated>
#     This code was generated by a tool.
#     Runtime Version: 4.0.30319.42000
#
#     Changes to this file may cause incorrect behavior and will be lost if 
#     the code is regenerated.
# </autogenerated>
#------------------------------------------------------------------------------

import System.Windows.Forms

class Form1_Designer(System.Windows.Forms.Form):
    
    def InitializeComponent(self):
        self.SuspendLayout()
        # 
        # Form1_Designer
        # 
        self.ClientSize = System.Drawing.Size(1777, 943)
        self.Name = "Form1_Designer"
        self.ResumeLayout(False)

