<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\..\..\..\Resources\Scripter.AlternetUI\CustomClass.cs" Link="CustomClass.cs" />
  </ItemGroup>
</Project>