<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ScriptProject</RootNamespace>
    <AssemblyName>ScriptProject</AssemblyName>
    <LangVersion>default</LangVersion>
  </PropertyGroup>
</Project>