<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>12.0</LangVersion>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>Sample.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>SQLDOMParser.AlternetUI</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Sample.ico" />
    <PackageReference Include="Alternet.Studio.Common.AlternetUI" Version="11.0.0" />
    <PackageReference Include="Alternet.Studio.Editor.Common.AlternetUI" Version="11.0.0" />
    <PackageReference Include="Alternet.Studio.Common" Version="11.0.0" />
    <PackageReference Include="Alternet.Studio.Editor.AlternetUI" Version="11.0.0" />
    <PackageReference Include="Alternet.Studio.Syntax.Parsers.Advanced" Version="11.0.0" />
    <PackageReference Include="Alternet.Studio.Syntax" Version="11.0.0" />
    <PackageReference Include="Alternet.UI" Version="1.1.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SqlServer.TransactSql.ScriptDom" Version="161.9123.0" />
  </ItemGroup>
  <!-- ====================================================== -->
</Project>