<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="pictureBox1.Image.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="pictureBox1.Image.png" />
  </ItemGroup>

</Project>