#------------------------------------------------------------------------------
# <autogenerated>
#     This code was generated by a tool.
#     Runtime Version: 4.0.30319.42000
#
#     Changes to this file may cause incorrect behavior and will be lost if 
#     the code is regenerated.
# </autogenerated>
#------------------------------------------------------------------------------

import System.Windows.Forms
import clr

class Form1_Designer(System.Windows.Forms.Form):
    
    def InitializeComponent(self):
        pass
