<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>Sample.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>AllQuickStarts.AlternetUI</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\CallMethod.Python\CallMethod.Python.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\CallMethod.TypeScript\CallMethod.TypeScript.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\CallMethod\CallMethod.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\CustomAssembly.Python\CustomAssembly.Python.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\CustomAssembly\CustomAssembly.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\CustomAssembly\ExternalAssembly\ExternalAssembly\ExternalAssembly.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\Debugger\DebuggerIntegration.Python\DebuggerIntegration.Python.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\Debugger\DebuggerIntegration\DebuggerIntegration.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\ExpressionEvaluation.Python\ExpressionEvaluation.Python.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\ExpressionEvaluation\ExpressionEvaluation.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\IsolatedScript\IsolatedScript.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\MemoryAssembly.Python\MemoryAssembly.Python.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\MemoryAssembly\MemoryAssembly.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\Mini.TypeScript\Mini.TypeScript.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\ObjectReference.Python\ObjectReference.Python.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\ObjectReference.TypeScript\ObjectReference.TypeScript.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\ObjectReference\ObjectReference.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\PackageReference\PackageReference.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\ScriptHostObject\ScriptHostObject.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\Threading.Python\Threading.Python.csproj" />
    <ProjectReference Include="..\..\Scripter.AlternetUI\QuickStarts\Threading\Threading.csproj" />
    <ProjectReference Include="..\Bookmarks\Bookmarks.csproj" />
    <ProjectReference Include="..\CodeCompletion\CodeCompletion.csproj" />
    <ProjectReference Include="..\CodeOutlining\CodeOutlining.csproj" />
    <ProjectReference Include="..\CodeSnippets\CodeSnippets.csproj" />
    <ProjectReference Include="..\Customize\Customize.csproj" />
    <ProjectReference Include="..\Gutter\Gutter.csproj" />
    <ProjectReference Include="..\HyperText\HyperText.csproj" />
    <ProjectReference Include="..\LineStyles\LineStyles.csproj" />
    <ProjectReference Include="..\Margin\Margin.csproj" />
    <ProjectReference Include="..\Miscellaneous\Miscellaneous.csproj" />
    <ProjectReference Include="..\Parsers\AdvancedSyntaxParsing\AdvancedSyntaxParsing.csproj" />
    <ProjectReference Include="..\Parsers\PowerFxSyntaxParsing\PowerFxSyntaxParsing.csproj" />
    <ProjectReference Include="..\Parsers\RoslynSyntaxParsing\RoslynSyntaxParsing.csproj" />
    <ProjectReference Include="..\Parsers\SQLDOMParser\SQLDOMParser.csproj" />
    <ProjectReference Include="..\Parsers\TextMateParsing\TextMateParsing.csproj" />
    <ProjectReference Include="..\Parsers\TypeScriptParsing\TypeScriptParsing.csproj" />
    <ProjectReference Include="..\Parsers\XAMLParsing\XamlParsing.csproj" />
    <ProjectReference Include="..\SearchReplace\SearchReplace.csproj" />
    <ProjectReference Include="..\SelectionAnchors\SelectionAnchors.csproj" />
    <ProjectReference Include="..\Selection\Selection.csproj" />
    <ProjectReference Include="..\SyntaxHighlighting\SyntaxHighlighting.csproj" />
    <ProjectReference Include="..\UndoRedo\UndoRedo.csproj" />
    <ProjectReference Include="..\VisualTheme\VisualTheme.csproj" />
    <ProjectReference Include="..\WordWrap\WordWrap.csproj" />
    <PackageReference Include="Alternet.Studio.Common.AlternetUI" Version="11.0.0" />
    <PackageReference Include="Alternet.Studio.Common" Version="11.0.0" />
    <PackageReference Include="Alternet.Studio.Editor.AlternetUI" Version="11.0.0" />
    <PackageReference Include="Alternet.Studio.Syntax" Version="11.0.0" />
    <PackageReference Include="Alternet.Studio.Syntax.Parsers.Roslyn" Version="11.0.0" />
    <PackageReference Include="Alternet.UI" Version="1.1.0" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Alternet.Demo.Run.Dark.bat" />
    <None Remove="Alternet.Demo.Run.sh" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Alternet.Demo.Run.sh">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Alternet.Demo.Run.Dark.bat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>